/**
 * Tiny client-side search over the JSON index emitted by
 * `/search-index.json` (see src/pages/search-index.json.ts). Unlike the old
 * Pagefind setup, this works identically in `dev`, `build` and on the deployed
 * site — the index is generated by Astro from the content collections.
 */
export type Doc = {
  type: 'flash' | 'term' | 'theme';
  title: string;
  url: string; // base-relative route, e.g. "/flashes/21/"
  body: string;
  number?: number;
  source?: string | null;
};

export type Hit = Doc & { score: number; excerptHtml: string };

let cache: Doc[] | null = null;
let inflight: Promise<Doc[]> | null = null;

/** Fetch (and memoise) the search index. Returns [] if it can't be loaded. */
export async function loadIndex(base: string): Promise<Doc[]> {
  if (cache) return cache;
  if (!inflight) {
    inflight = fetch(`${base}search-index.json`)
      .then((r) => (r.ok ? (r.json() as Promise<Doc[]>) : []))
      .then((d) => (cache = d))
      .catch(() => (cache = []));
  }
  return inflight;
}

/** Prefix a base-relative route with the deploy base path. */
export function linkWithBase(base: string, url: string): string {
  return `${base.replace(/\/$/, '')}${url.startsWith('/') ? url : `/${url}`}`;
}

const esc = (s: string) =>
  s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));

const escRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export function searchDocs(docs: Doc[], query: string, limit = 20): Hit[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const tokens = q.split(/\s+/).filter(Boolean);
  const hits: Hit[] = [];

  for (const d of docs) {
    const title = d.title.toLowerCase();
    const body = d.body.toLowerCase();
    let score = 0;
    let all = true;
    for (const t of tokens) {
      const inTitle = title.includes(t);
      const inBody = body.includes(t);
      if (!inTitle && !inBody) {
        all = false;
        break;
      }
      score += (inTitle ? 6 : 0) + (inBody ? 1 : 0);
      if (title.startsWith(t)) score += 4;
    }
    if (!all) continue;
    // Small nudge so the exact phrase ranks above scattered tokens.
    if (title.includes(q) || body.includes(q)) score += 3;
    hits.push({ ...d, score, excerptHtml: excerpt(d.body, tokens) });
  }

  hits.sort((a, b) => b.score - a.score || a.title.localeCompare(b.title));
  return hits.slice(0, limit);
}

function excerpt(body: string, tokens: string[]): string {
  const lower = body.toLowerCase();
  let pos = -1;
  for (const t of tokens) {
    const i = lower.indexOf(t);
    if (i >= 0 && (pos < 0 || i < pos)) pos = i;
  }
  const start = pos < 0 ? 0 : Math.max(0, pos - 60);
  let snippet = body.slice(start, start + 180);
  if (start > 0) snippet = `…${snippet}`;
  if (start + 180 < body.length) snippet = `${snippet}…`;

  let html = esc(snippet);
  for (const t of tokens) {
    html = html.replace(new RegExp(`(${escRe(t)})`, 'ig'), '<mark>$1</mark>');
  }
  return html;
}
