import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';

/**
 * Build the bilingual client search index from the content collections.
 * Generated by Astro at build time (static `search-index.json`) and served live
 * in `dev`, so search works in every environment and in both locales.
 */

function plain(md: string): string {
  return md
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/[#>*_~`|]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export const GET: APIRoute = async () => {
  const [flashes, glossary, themes] = await Promise.all([
    getCollection('flashes'),
    getCollection('glossary'),
    getCollection('themes'),
  ]);

  type Doc = Record<string, unknown>;
  const docs: Doc[] = [];

  for (const f of flashes) {
    const d = f.data;
    const outline = (d.outline ?? []).map((o) => `${o.heading} ${o.note ?? ''}`).join(' ');
    const outlineTr = (d.outline ?? [])
      .map((o) => `${o.headingTr ?? o.heading} ${o.noteTr ?? ''}`)
      .join(' ');
    const concepts = (d.keyConcepts ?? []).join(' ');
    const body = [d.essence, outline, concepts, d.context?.note, d.titleTr, plain((f as { body?: string }).body ?? '')]
      .filter(Boolean)
      .join(' ');
    const bodyTr = [d.essenceTr, outlineTr, concepts, d.context?.noteTr, plain(d.summaryTr ?? '')]
      .filter(Boolean)
      .join(' ');
    docs.push({
      type: 'flash',
      number: d.number,
      title: d.title,
      titleTr: d.titleTr ?? d.title,
      url: `/flashes/${f.id}/`,
      body,
      bodyTr: bodyTr || body,
      source: d.source?.erisaleUrlEn ?? null,
      sourceTr: d.source?.erisaleUrlTr ?? d.source?.erisaleUrlEn ?? null,
    });
  }

  for (const g of glossary) {
    const d = g.data;
    docs.push({
      type: 'term',
      title: d.term,
      titleTr: d.term,
      url: `/glossary/${d.id}/`,
      body: [d.definitionEn, d.id].filter(Boolean).join(' '),
      bodyTr: [d.definitionTr ?? d.definitionEn, d.id].filter(Boolean).join(' '),
    });
  }

  for (const t of themes) {
    const d = t.data;
    docs.push({
      type: 'theme',
      title: d.name,
      titleTr: d.nameTr ?? d.name,
      url: `/themes/${d.id}/`,
      body: d.description,
      bodyTr: d.descriptionTr ?? d.description,
    });
  }

  return new Response(JSON.stringify(docs), {
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  });
};
